db.habitaciones.insert([
  {
    nombre: "101",
    tipo: "simple",
    capacidad: 1,
    tarifa: 40.00,
    estado: "disponible",
  },
  {
    nombre: "102",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "103",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "104",
    tipo: "doble",
    capacidad: 2,
    tarifa: 80.00,
    estado: "disponible",
  },
  {
    nombre: "105",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "106",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "107",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 45.00,
    estado: "disponible",
  },
  {
    nombre: "201",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "202",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "203",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "204",
    tipo: "doble",
    capacidad: 3,
    tarifa: 75.00,
    estado: "disponible",
  },
  {
    nombre: "205",
    tipo: "doble",
    capacidad: 3,
    tarifa: 75.00,
    estado: "disponible",
  },
  {
    nombre: "206",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "207",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 50.00,
    estado: "disponible",
  },
  {
    nombre: "208",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 45.00,
    estado: "disponible",
  },
  {
    nombre: "209",
    tipo: "matrimonial",
    capacidad: 2,
    tarifa: 45.00,
    estado: "disponible",
  }
]);
